kind: Deployment
apiVersion: apps/v1
metadata:
  name: nautible-app-ms-product
  labels:
    app.kubernetes.io/name: nautible-app-ms
    app.kubernetes.io/instance: nautible-app-ms-product
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: nautible
    app.kubernetes.io/managed-by: manual
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: nautible-app-ms-product
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: product-db.vpc.nautible.com
