kind: Deployment
apiVersion: apps/v1
metadata:
  name: nautible-app-ms-product
  namespace: nautible-app-ms
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: nautible-app-ms-product
          env:
            - name: QUARKUS_PROFILE
              value: local-dev
            - name: JAVA_ENABLE_DEBUG
              value: "true"
            - name: JAVA_DEBUG_PORT
              value: "5005"
            - name: DB_HOST
              value: nautible-app-ms-product-mysql
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: DATABASE_USER
            - name: DB_PW
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DATABASE_PW
          ports:
            - name: jvm-debug
              protocol: TCP
              containerPort: 5005

