kind: Deployment
apiVersion: apps/v1
metadata:
  name: nautible-app-ms-product
  namespace: nautible-app-ms
  labels:
    app.kubernetes.io/name: nautible-app-ms-product
    app.kubernetes.io/instance: nautible-app-ms-product
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: nautible
    app.kubernetes.io/managed-by: manual
spec:
  template:
    spec:
      containers:
        - name: nautible-app-ms-product
          image: public.ecr.aws/nautible/nautible-app-ms-product:2397a66d10f95f7a257c2d8b8ee955ce13c96f3d
          imagePullPolicy: Always
          env:
            - name: QUARKUS_PROFILE
              value: aws-dev
            - name: DB_HOST
              value: product-db.vpc.nautible-dev.com
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secret-nautible-app-ms-product-db
                  key: DATABASE_USER
            - name: DB_PW
              valueFrom:
                secretKeyRef:
                  name: secret-nautible-app-ms-product-db
                  key: DATABASE_PW

