kind: Deployment
apiVersion: apps/v1
metadata:
  name: nautible-app-product
  labels:
    app.kubernetes.io/name: nautible-app-product
    app.kubernetes.io/instance: nautible-app-product
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: nautible
    app.kubernetes.io/managed-by: manual
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: nautible-app-product
      app.kubernetes.io/component: app
  replicas: 2
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nautible-app-product
        app.kubernetes.io/instance: nautible-app-product
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/component: app
        app.kubernetes.io/part-of: nautible
        app.kubernetes.io/managed-by: manual
    spec:
      containers:
        - name: nautible-app-product
          image: public.ecr.aws/nautible/nautible-app-product:f32d06c1dde44a74658ce52a96eeceed8ec40836
          imagePullPolicy: Always
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
status: {}
