kind: Deployment
apiVersion: apps/v1
metadata:
  name: nautible-app-ms-product
  namespace: nautible-app-ms
  labels:
    app.kubernetes.io/name: nautible-app-ms-product
    app.kubernetes.io/instance: nautible-app-ms-product
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: nautible
    app.kubernetes.io/managed-by: manual
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: nautible-app-ms-product
      app.kubernetes.io/component: app
  replicas: 2
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nautible-app-ms-product
        app.kubernetes.io/instance: nautible-app-ms-product
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/component: app
        app.kubernetes.io/part-of: nautible
        app.kubernetes.io/managed-by: manual
    spec:
      containers:
        - name: nautible-app-ms-product
          image: public.ecr.aws/nautible/nautible-app-ms-product:dummy
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
      serviceAccount: nautible-app-ms-sa
      serviceAccountName: nautible-app-ms-sa
