kind: Deployment
apiVersion: apps/v1
metadata:
  name: nautible-app-ms-product
  namespace: nautible-app-ms
  labels:
    app.kubernetes.io/name: nautible-app-ms-product
    app.kubernetes.io/instance: nautible-app-ms-product
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: nautible
    app.kubernetes.io/managed-by: manual
spec:
  template:
    spec:
      containers:
        - name: nautible-app-ms-product
          image: nautibledevacr.azurecr.io/nautible-app-ms-product:c5d8fa8d93f9d10a81767314c9daea514e2db7b6
          imagePullPolicy: Always
          env:
            - name: QUARKUS_PROFILE
              value: azure-dev
            - name: DB_HOST
              value: product-fs.product-fs.private.mysql.database.azure.com
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secret-nautible-app-ms-product-db
                  key: DATABASE_USER
            - name: DB_PW
              valueFrom:
                secretKeyRef:
                  name: secret-nautible-app-ms-product-db
                  key: DATABASE_PW

